version: "3"

services:
  linglink-back:
    build:
      dockerfile: Dockerfile
    expose:
      - 8080
    container_name: linglink-back
    networks:
      - backend
    ports:
      - 8080:8080
    restart: always
    environment:
      - JASYPT_KEY=${JASYPT_KEY}
      - ENV CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - linglink-back
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
