logging:
  config:
    classpath: logback.yml

spring:
  data:
    mongodb:
      uri:
        ENC(YyJZtbSiGTlWqn54PXlPtbGavWNajLJS5dcpUTY6oeI6kEsGpohOGFwIyWYIXT26aP5n4SZFaZnMGaZAqPr3pfqR1SWXAVQJugvO/EL1yhdkVsbtrKwpciKCA1IasFqSUZdsAOmq3F0=)
      database:
        lingualink
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
